version: '3.5'
services:
  php:
    image: dx46/php-fpm:7.4
    networks:
      app_net:
        ipv4_address: 172.18.0.2
    container_name: php
    volumes:
      - $HOME/Public/projek/:/var/www/html/
      - .phplog:/var/log/php-fpm
  nginx:
    image: nginx:alpine 
    container_name: nginx
    depends_on:
      - php
      - db
    networks:
      app_net:
        ipv4_address: 172.18.0.3
    ports:
      - "8080:80"
    volumes:
      - $HOME/Public/projek/:/var/www/html/
      - $HOME/Public/dok/:/var/www/html/dok/
      - .nginxlog:/var/log/nginx
      - ./etc/site.conf:/etc/nginx/conf.d/site.conf
  db:
    image: postgres:12-alpine
    container_name: db
    volumes:
      - .postg:/var/lib/pgsql/data/
    networks:
      app_net:
        ipv4_address: 172.18.0.4
    environment:
      - POSTGRES_USER=petro
      - POSTGRES_PASSWORD=udin4j4
networks:
  app_net:
    ipam:
      driver: default 
      config:
        - subnet: 172.18.0.0/24
