version: '3.5'
services:
  php:
    image: dx46/php-fpm:7.2
    networks:
      app_net:
        ipv4_address: 172.18.0.2
    container_name: php
    volumes:
      - $HOME/Public/dev/learn/lpmj/ci3:/var/www/html/
      - .phplog:/var/log/php-fpm
  nginx:
    image: nginx:1.14-alpine 
    container_name: nginx
    depends_on:
      - php
      - db
    networks:
      app_net:
        ipv4_address: 172.18.0.3
    ports:
      - "8080:80"
    volumes:
      - $HOME/Public/dev/learn/lpmj/ci3:/var/www/html/
      - .nginxlog:/var/log/nginx
      - ./etc/site.conf:/etc/nginx/conf.d/site.conf
  db:
    image: dx46/mariadb-alpine
    container_name: db
    networks:
      app_net:
        ipv4_address: 172.18.0.4
    environment:
      - MYSQL_USER=mardin
      - MYSQL_PASSWORD=udin4j4
networks:
  app_net:
    ipam:
      driver: default 
      config:
        - subnet: 172.18.0.0/24
