version: '2'
services:
    web:
        image: dx46/php56fpm-with-mysql-postgresql
        container_name: php
        restart: always
        volumes:
            - $HOME/public_html:/var/www/html/
            - .phplog:/var/log/php-fpm
        depends_on:
            - db
    db:
        image: dx46/mariadb-alpine 
        container_name: mariadb
        volumes:
            - .mysql:/var/lib/mysql
            - ./etc/mariadb_init.sh:/mariadb_init.sh
            - ./etc/run.sh:/run.sh
        restart: always
        #environment:
        #        MYSQL_ROOT_PASSWORD: udin4j4
        #        MYSQL_DATABASE: testdb
        #        MYSQL_USER: udin
        #        MYSQL_PASSWORD: rahasia
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        restart: always
        ports:
            - "8080:80"
        volumes:
            - .nginxlog:/var/log/nginx
            - $HOME/public_html:/var/www/html
            - ./etc/site.conf:/etc/nginx/conf.d/site.conf
        depends_on:
            - web
